name: Build LaTeX document
on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - '**.bib'
      - '**.cls'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up LaTeX environment
        uses: xu-cheng/latex-action@v3
        with:
          root_file: rapport/main.tex
        env:
          TEXINPUTS: ".:.//:./../scripts//"
      - name: Build Executive Summary
        uses: xu-cheng/latex-action@v3
        with:
          root_file: rapport/summary.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: *.pdf
          if-no-files-found: error